### 2.4.2 Arrays

In order to initialize an array, we can use the numpy zeros method.  
we first specify the shape, then the data type

In [95]:
import numpy as np

a = np.zeros(4, float)
a



array([0., 0., 0., 0.])

In [96]:
b = np.zeros([3,4], float)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Alternatively, if we plan to change the numbers, we can save time using np.empty()

In [97]:
c = np.empty([3, 4], float)
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

We can also take a pre-existing python list and convert it into an array:

In [98]:
d = [1.0, 2.5, 3.2]
e = np.array(d, float)
e

array([1. , 2.5, 3.2])

or in the case of an n-dimensional array:

In [99]:
a = [0, 2, 4]
b = [1, 2, 4]

c = np.array([a, b], int)
c

array([[0, 2, 4],
       [1, 2, 4]])

accessing elements in an array:

In [100]:
a = np.zeros([2,2], int) # 2x2 matrix of zeros
a[0,1] = 1  # row 0 column 1 = 1
a[1,0] = -1 # row 1 column 0 = -1

a

array([[ 0,  1],
       [-1,  0]])

We can do math on entire arrays, with each element having the operation applied to it

In [101]:
a = np.array([[1,2,3],
              [1,2,3]
            ], int)

a*2

array([[2, 4, 6],
       [2, 4, 6]])

In [102]:
b = np.array([[1,2,3],
              [1,2,3]
            ], int)

a - 2*b

array([[-1, -2, -3],
       [-1, -2, -3]])

if we multiply two arrays together, we do not get dot product, instead each element multiplies its corresponding element

In [103]:
a * b

array([[1, 4, 9],
       [1, 4, 9]])

in order to get dot product, we must import it

In [104]:
from numpy import dot, array

a = array([[1,2],[3,4]], int)
b = array([[2,4],[6,8]], int)
c = array([[1,0],[0,1]], int)

dot(a, b) + 2*c

array([[16, 20],
       [30, 46]])

### important to note that outside of using two vectors, np.dot actually is just doing matrix multiplication  
I prefer to use the matrix multiplication operator for clarity

In [105]:
a @ b + 2*c

array([[16, 20],
       [30, 46]])